### ISSUE TITLE
Mask Cloud without option L2W_mask = True

### ISSUE THREAD

**Issue by hanamthang** [acolite/acolite#14]
Hi Quinten, 

It is not an issue, rather a kindly request for feature improvement.

At the current version of ACOLITE, the cloud will be masked when L2W_mask = True. Do we have any options that support a cloud masking without setting True for L2w_mask? My study areas are always exposed and submerged, so usually I do not mask L2W. 

Regrads,
Thang

**Comment by acolite** [comment]
Hi Thang

Currently the only cloud masking in ACOLITE is the non-water masking in the L2W files. There are some external masking tools that can be used (e.g. FMask, IdePix) to compute a mask that can then be applied to the ACOLITE outputs using some simple postprocessing code.

I can see some ways to add a mask layer to the L2R file using some simple thresholding masks, will keep that in mind.

Quinten

**Comment by hanamthang** [comment]
Thank you very much for your time. Hopefully new feature will come in the near future. 

Best regards,
Thang
