### ISSUE TITLE
Processing of WorldView II MS data does not work

### ISSUE THREAD

**Issue by dpoursanidis** [acolite/acolite#19]
Hi

Am trying to use ACOLITE for WVII processing, the MS part.
I point to the directory that contains the following

![image](https://user-images.githubusercontent.com/8640644/146777103-c1147a65-76c6-4a9a-8962-30398e9dd2be.png)

but i recieve the following in the cmd

![image](https://user-images.githubusercontent.com/8640644/146777182-2fa40464-15ff-41af-ac78-db406910d917.png)

i use the GUI

![image](https://user-images.githubusercontent.com/8640644/146777269-347aaff4-76ef-4829-a589-e8f4d5e56717.png)

Any advice on that?

**Comment by acolite** [comment]
Hi Dimitris

Could you check whether the XML metadata file has a lowercase (.xml) or uppercase (.XML) extension? ACOLITE currently expects it to be in uppercase.

I presume the XML contains the SATID value "WV02"?

Quinten

**Comment by dpoursanidis** [comment]
[20SEP17090319-M2AS-21EUSI-1869-01.zip](https://github.com/acolite/acolite/files/7750988/20SEP17090319-M2AS-21EUSI-1869-01.zip)

Here it is. 

XML in uppercase and SATID value are correct

**Comment by acolite** [comment]
Hi Dimitris

This XML indeed parses fine here. Perhaps you are running into Windows path length limitations? Could you move the 21EUSI-1869-01_MUL directory to the base level of D:\ and try processing that?

Quinten

**Comment by dpoursanidis** [comment]
Same again

![image](https://user-images.githubusercontent.com/8640644/146904310-2f049772-87d8-48e1-85dc-bd27b397e22a.png)

Am running from the GUI. Did that make the diff and i have to do something else?

**Comment by acolite** [comment]
For some reason it is not finding the metadata file. Perhaps it is caused by your system localisation?

Could you try entering the inputfile manually as D:/21EUSI-1869-01_MUL/

Quinten

**Comment by dpoursanidis** [comment]
Nothing happen even by following your instructions. Test Sentinel 2 L1C and works. So ACOLITE does not recognize the WVII. Shall i send  you over mail to test it?

**Comment by acolite** [comment]
Hi Dimitris

OK, please send me the file by email. I have a feeling it will work on my end, but I can give it a shot!

I will probably need to manage Windows file paths better.

Quinten

**Comment by dpoursanidis** [comment]
Just send ;)

**Comment by acolite** [comment]
Dear Dimitris, I am able to process your scene 21EUSI-1869-01_E726422_FL00-P01B4DL/21EUSI-1869-01_MUL with the latest binary release: https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?f=3&t=323

Could you check if this resolves your issue?

Quinten

**Comment by dpoursanidis** [comment]
Hi Quinten

A quick run with defaults give me results

![image](https://user-images.githubusercontent.com/8640644/155344641-927e085b-2397-4b7c-903f-38b37a3f83f9.png)

and the cmd run attached

[ACOLITE new report.txt](https://github.com/acolite/acolite/files/8125270/ACOLITE.new.report.txt)

Not yet open files but it seems ok.

**Comment by acolite** [comment]
Hi Dimitris

That looks good indeed. Thanks for checking!

Quinten
