### ISSUE TITLE
KeyError: 'PRODUCT_URI'

### ISSUE THREAD

**Issue by ausiasrt** [acolite/acolite#22]
Hi,
I needed to apply Acolite for a Sentinel 2 image from 2017 but I constantly get this error:

Restored settings file C:/EspaiProves/Imatges de prova S2A/ajustos.txt
Running ACOLITE processing on win32
ACOLITE processing messages will be logged to file.
Processing error:
'PRODUCT_URI'
Traceback (most recent call last):
  File "C:\acolite\acolite\acolite\acolite_gui.py", line 25, in run
    mp.Process.run(self)
  File "C:\Users\aurocta\Desktop\WPy64-3980\python-3.9.8.amd64\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\acolite\acolite\acolite\acolite_run.py", line 111, in acolite_run
    ret = ac.acolite.acolite_l1r(bundle, setu_l1r)
  File "C:\acolite\acolite\acolite\acolite_l1r.py", line 47, in acolite_l1r
    l1r_files, setu = ac.sentinel2.l1_convert(bundle, settings = setu)
  File "C:\acolite\acolite\sentinel2\l1_convert.py", line 143, in l1_convert
    mgrs_tile = meta['PRODUCT_URI'].split('_')[-2]
KeyError: 'PRODUCT_URI'

I redownloaded the image and I get the same message. By the other hand, I tried to run Acolite using the same configuration but with other file (from 2021) and everything worked fine.
Maybe Copernicus changed the S2 metadata files between 2017 and 2021 and Acolite only supports the lastest version?

Thanks in advance.

**Comment by acolite** [comment]
Could you specify which product you are trying to process? Since the mgrs_tile is overwritten in the next line, this line of code can probably be removed to fix this issue: https://github.com/acolite/acolite/blob/9378fffd5290a330b4f6acbdd397fe11e0d994ad/acolite/sentinel2/l1_convert.py#L143

Quinten

**Comment by ausiasrt** [comment]
I want to process a Sentinel 2A Level 1-C (S2A_MSIL1C_20170410T103021_N0204_R108_T31SED_20200708T204702)
I commented that line and now it works, thanks!

Ausiàs.

**Comment by acolite** [comment]
Thanks Ausiàs - I have now also commented out that line in the code: https://github.com/acolite/acolite/commit/2733e9d66118bb4122aaa7431b860aee932a3049

Quinten
