### ISSUE TITLE
Compiling libRadtran for ACOLITE/TACT collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by acolite** [acolite/acolite#26]
I successfully compiled and executed the ACOLITE with TACT option for Landat image in the linux Lubuntu distro. Despite, I can not do the same for the arch linux Manjaro distro. It still throw the error when compiling the libRadtran in python27 environment:

`
compiling sofi.c
   linking ../bin/sofi
/usr/bin/ld: ../lib/libRadtran_c.a(uvspecrandom.o):/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/softl/atmospheric/acolite/external/libRadtran-2.0.2/libsrc_c/uvspecrandom.c:39: multiple definition of `uvspecrng'; ../lib/libRadtran_c.a(mystic.o):/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/softl/atmospheric/acolite/external/libRadtran-2.0.2/libsrc_c/mystic.c:145: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:234: ../bin/sofi] Error 1
make[1]: Leaving directory '/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/softl/atmospheric/acolite/external/libRadtran-2.0.2/src'
make: *** [Makefile:39: all] Error 2
`

So, I think the problem might regrading the distro itself.

_Originally posted by @hanamthang in https://github.com/acolite/acolite/issues/25#issuecomment-1046187052_

**Comment by acolite** [comment]
Hi Thang

This seems related to the default behaviour of your compiler. I managed to fix this error on Arch Linux by editing the Makeconf file to include the -fcommon flag. Run "nano Makeconf" in your libRadtran-2.0.2 folder and change the line (around L97?):

`CFLAGS = -g -O2`

to

`CFLAGS = -g -O2 -fcommon`

Let me know how it goes!

Quinten

**Comment by hanamthang** [comment]
Wow, thank you very much, just a line and it saved me hours of searching. I can compiled the libRadtran in Arch linux now. 

Many thanks, 
Thang

**Comment by acolite** [comment]
Thanks for the update Thang, glad it worked! I also had to search a bit to figure out the linker behaviour. ;-)

Quinten
