### ISSUE TITLE
Which Planet files needed for ACOLITE processing?

### ISSUE THREAD

**Issue by JackLidge** [acolite/acolite#29]
Hi Quinten,

I've been looking into processing Planet data with ACOLITE, but I'm having some errors with proj. I'll get the full error output for you tomorrow as I'm not on my work laptop at the moment, but I wanted to check quickly I'm ordering the correct files from the Planet API. I think these should be the same as the ones suggested in the documentation but wanted to be absolute certain they are the correct ones.

So far, I've tested atmospheric correction providing the following files to ACOLITE:
*_1A_udm2.tif
*_1B_AnalyticMS_8b.tif
*_1B_AnalyticMS_8b_metadata.xml
*_1B_AnalyticMS_RPC.TXT

Thanks very much!

**Comment by acolite** [comment]
Hi Jack

For 8 band SD processing these files are needed:

_AnalyticMS_8b.tif
_AnalyticMS_8b_metadata.xml

from the clipping API they have an extra _clip at the end:

_AnalyticMS_8b_clip.tif
_AnalyticMS_8b_metadata_clip.xml

You can provide a path to the directory containing these files, or to the zipfile directly. If you unzip the bundles, you can leave the files in the "files" or other directories in the extracted zip files, as these folders are also scanned: https://github.com/acolite/acolite/blob/94703f1f1bdf250821520afc861a32ac48d6f74c/acolite/planet/bundle_test.py#L24-L27

If you order through the Planet Explorer these are called "Analytic radiance (TOAR) - 8 band" and in the API I think you need ortho_analytic_8b assets with a analytic_8b_udm2 bundle.

Edit: The proj error may have something to do with the version or source of Python packages you are using.

I hope this helps!

Quinten

**Comment by JackLidge** [comment]
Great thanks very much! I'll be looking into this more tomorrow, so will check I'm definitely getting the right bundle.

Yes, I thought it might be due to the python packages, I will also check them tomorrow.

**Comment by JackLidge** [comment]
Hi Quinten,

Thanks for your help with this, it seems I was indeed downloading the wrong bundle, I was previously downloading the `basic_analytic_8b_udm2` bundle. I switched this morning to the `analytic_8b_udm2` bundle and successfully processed the Planet tile!

**Comment by acolite** [comment]
Thanks for the update Jack, I have added to the manual for future releases:

> For SuperDove processing order the "Analytic radiance (TOAR) - 8 band" data from the Explorer, or analytic_8b_udm2 bundles through the API.


Quinten
