### ISSUE TITLE
KeyError: 'Blue-to_reflectance' for Planet image processing

### ISSUE THREAD

**Issue by hanamthang** [acolite/acolite#3]
Hi Quinten, 

I tried the Acolite generic version for Planet Scope 4 bands processing to the Rrs. Error as follows: 

`Starting conversion of 1 scenes
Importing metadata from /home/metal/Downloads/Compressed/planet/PSScene4Band
Writing geolocation lon/lat
Wrote lon
Wrote lat
Traceback (most recent call last):
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/launch_acolite.py", line 58, in <module>
    launch_acolite()
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/launch_acolite.py", line 52, in launch_acolite
    ac.acolite.acolite_run(args.settings, inputfile=inputfile, output=output)
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/acolite/acolite/acolite_run.py", line 89, in acolite_run
    ret = ac.acolite.acolite_l1r(bundle, setu_l1r)
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/acolite/acolite/acolite_l1r.py", line 135, in acolite_l1r
    l1r_files = ac.planet.l1_convert(bundle, output=output_,
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/acolite/planet/l1_convert.py", line 299, in l1_convert
    data = data.astype(float) * float(meta['{}-{}'.format(b,'to_reflectance')])
KeyError: 'Blue-to_reflectance'
`
Attached is the setting file. 
[defaults.txt](https://github.com/acolite/acolite/files/6490783/defaults.txt)

Could you help me with any advice?

Many thanks,
Thang

**Comment by acolite** [comment]
Hi Thang

Thanks for your message - it seems like some keys are missing from the metadata. Which type of Planet data do you have? Can you list the files that are in your input directory /home/metal/Downloads/Compressed/planet/PSScene4Band ?

Quinten

**Comment by hanamthang** [comment]
List of files: 
/home/metal/Downloads/Compressed/files/PSScene4Band:
- 20210514_003233_1050_metadata.json
- folder: uncalibrated_dn_udm2
In folder uncalibrated_dn_udm2:
- 20210514_003233_1050_3B_AnalyticMS_DN_metadata.xml
- 20210514_003233_1050_3B_AnalyticMS_DN_udm.tif
- 20210514_003233_1050_3B_AnalyticMS_DN.tif
- 20210514_003233_1050_3B_udm2.tif

At first, I ran ACOLITE for this folder but ACOLITE can not detect the input. 
Then, I changed the name of file, and only keep the files as follows (in the 
/home/metal/Downloads/Compressed/planet/PSScene4Band): 

- 20210514_023208_80_242a_3B_AnalyticMS_metadata.xml
- 20210514_023208_80_242a_3B_AnalyticMS.tif

but the "KeyError: 'Blue-to_reflectance'" appeared. 

Thang

**Comment by acolite** [comment]
Hi Thang

ACOLITE can process "analytic" data and not "uncalibrated" data. Presumably these files were downloaded from the Planet Explorer? In the order screen you have the option of selecting "Analytic Radiance (TOAR)" instead of "Uncalibrated DN". Could you give that a try?

Quinten

**Comment by hanamthang** [comment]
Ah, understood. I will tried it again and inform you. 

Many thanks, 
Thang

**Comment by hanamthang** [comment]
I tried another TOA scene of Planet Scope, the ACOLITE worked but still the error as follows: 

Run ID - 20210517_161157
/home/metal/Documents238/research_paper/seagrass_tgch21/files/PSScene4Band/20210514_023208_80_242a/analytic_udm2
/home/metal/Documents238/research_paper/seagrass_tgch21/files/PSScene4Band/20210514_023208_80_242a/analytic_udm2/20210514_023208_80_242a_3B_AnalyticMS_metadata.xml
/home/metal/Documents238/research_paper/seagrass_tgch21/files/PSScene4Band/20210514_023208_80_242a/analytic_udm2/Rrsg/acolite_run_20210517_161157_l1r_settings.txt
Starting conversion of 1 scenes
Importing metadata from /home/metal/Documents238/research_paper/seagrass_tgch21/files/PSScene4Band/20210514_023208_80_242a/analytic_udm2
Writing geolocation lon/lat
Wrote lon
Wrote lat
(9518, 13474)
Converting bands: Wrote rhot_492 ((9518, 13474))
(9518, 13474)
Converting bands: Wrote rhot_566 ((9518, 13474))
(9518, 13474)
Converting bands: Wrote rhot_666 ((9518, 13474))
(9518, 13474)
Converting bands: Wrote rhot_866 ((9518, 13474))
Conversion took 232.2 seconds
Created /home/metal/Documents238/research_paper/seagrass_tgch21/files/PSScene4Band/20210514_023208_80_242a/analytic_udm2/Rrsg/PlanetScope_242a_2021_05_14_02_32_08_CauHai_LapAn_L1R.nc
Running acolite for /home/metal/Documents238/research_paper/seagrass_tgch21/files/PSScene4Band/20210514_023208_80_242a/analytic_udm2/Rrsg/PlanetScope_242a_2021_05_14_02_32_08_CauHai_LapAn_L1R.nc
Scene too recent to get ancillary data
Using DSF atmospheric correction
Processing with 35 tiles (5x7)
Writing lon
Wrote lon
Writing lat
Wrote lat
Blue rhot_492
PlanetScope_22/BBlue ACOLITE-LUT-202102-MOD1 took 0.014s (StdLUT)
PlanetScope_22/BBlue ACOLITE-LUT-202102-MOD2 took 0.015s (StdLUT)
Green rhot_566
PlanetScope_22/BGreen ACOLITE-LUT-202102-MOD1 took 0.014s (StdLUT)
PlanetScope_22/BGreen ACOLITE-LUT-202102-MOD2 took 0.014s (StdLUT)
Red rhot_666
PlanetScope_22/BRed ACOLITE-LUT-202102-MOD1 took 0.013s (StdLUT)
PlanetScope_22/BRed ACOLITE-LUT-202102-MOD2 took 0.013s (StdLUT)
NIR rhot_866
PlanetScope_22/BNIR ACOLITE-LUT-202102-MOD1 took 0.014s (StdLUT)
PlanetScope_22/BNIR ACOLITE-LUT-202102-MOD2 took 0.014s (StdLUT)
Choosing best fitting model: min_drmsd
Computing RMSD for model ACOLITE-LUT-202102-MOD1
Computing RMSD for model ACOLITE-LUT-202102-MOD2
use_revlut False
Wrote rhot_492
Computing surface reflectance Blue 492 0.983
Interpolating tiles
Killed


Thang

**Comment by acolite** [comment]
Hi Thang

The processing was probably Killed because of excessive RAM use in the tiled processing of this large scene.

For PlanetScope processing I would recommend using the fixed DSF (see PlanetScope default settings in acolite/config/defaults/): dsf_path_reflectance=fixed

Quinten

**Comment by hanamthang** [comment]
Thank you very much for your suggestion. The ACOLITE successfully processed the scene now. 

To save the RAM, can I subset to a smaller area of the only study site? Will this subset impact on the quality of the atmospheric correction? 

Thang

**Comment by acolite** [comment]
Hi Thang

Since you are able to process the scene I will close the issue. Discussion of settings and performance we can perhaps continue on the ACOLITE forum: https://odnature.naturalsciences.be/remsem/acolite-forum/index.php

You can indeed subset the scene to use less RAM. The tiled or per pixel processing methods will use much more RAM since they will interpolate the atmospheric parameters to create full scene datasets (9518 x 13474 pixels in your case), while for fixed DSF the atmospheric parameters are just a single value.

In general the DSF performs a bit better for a specific area when subsetting (some of this is explored for other sensors in https://doi.org/10.1364/OE.397456 and in Appendix B of https://doi.org/10.1016/j.rse.2021.112284). The larger the scene, the more likely it is you will have darker pixels present, and hence for large scenes there could be an underestimation of the path reflectance, and overestimation of target reflectance. For PlanetScope the results are quite good even for very small regions of interest (1.2 x 1.2 km and 3 x 3 km, see https://doi.org/10.1364/OE.27.0A1372 and  https://doi.org/10.1364/OE.397456)

You can specify a region of interest in the settings file, either as a four element limit of bounding latitudes and longitudes:
limit=S,W,N,E

or as a polygon file (in geojson format for example):
polygon=/path/to/region.geojson

Quinten

**Comment by hanamthang** [comment]
Very details. My appreciation to your work. :-) 

Thang
