### ISSUE TITLE
Wrong address for LUT downloads Landsat 5 TM

### ISSUE THREAD

**Issue by hanamthang** [acolite/acolite#30]
Hi Quinten, 

I currently process an L5 TM scene but ACOLITE can not download the LUT `ACOLITE-LUT-202102-MOD1-0750mb_L5_TM.nc`. I noted two issues: 

- The link seems to be changed from `LUT https://raw.githubusercontent.com/acolite/acolite_luts` to `https://github.com/acolite/acolite_luts/tree/main`.
- There is no file named `ACOLITE-LUT-202102-MOD1-0750mb_L5_TM.nc` under the folder L5_TM in the GitHub repository. 

Could you pls have a check for this issue? 

Many thanks,
Thang

**Comment by acolite** [comment]
Hi Thang

Thanks for your question! This LUT does indeed not exist. You have probably re-used (parts of) an old settings file for your run. If you make custom settings files, it is best to only add the settings you want to change in a "minimal" settings file.

The new default settings contain references the new LUTs which where updated with an additional pressure step:

> luts=ACOLITE-LUT-202110-MOD1,ACOLITE-LUT-202110-MOD2
> luts_pressures=500,750,1013,1100

You likely have a luts line with the old LUT names in your custom settings file. I would recommend to remove the luts and/or luts_pressures lines from your custom settings file. If you want to keep using the 202102 version of the LUT - I see no reason to do so - you could alternatively add these lines to your custom settings file, i.e. including the available pressure steps:

> luts=ACOLITE-LUT-202102-MOD1,ACOLITE-LUT-202102-MOD2
> luts_pressures=500,1013,1100

I hope this helps!

Quinten
