### ISSUE TITLE
About Landsat9 processed

### ISSUE THREAD

**Issue by LH002** [acolite/acolite#31]
Dear Quinten:
    I had a problem when I was processing landsat9 data. After landsat9 data is processed with L1 level data, there is no movement, no processing movement. The following is my processing interface:
![1650356841(1)](https://user-images.githubusercontent.com/35960535/163959796-e3781ad5-9868-4038-ab6b-02ce8e902b2f.png)
![1650357008(1)](https://user-images.githubusercontent.com/35960535/163960099-85d8093e-6f66-48f9-96f3-522c6f6e5a01.png)
Why do I encounter this problem?

**Comment by acolite** [comment]
Hi

Processing the same scene with the settings in the GUI (Binary 20220222.0) works fine here!

![L9_OLI_2022_02_26_02_31_15_119038_L2R_rgb_rhos](https://user-images.githubusercontent.com/26734727/165037329-8ee9da4b-2fa7-4db1-af4a-b64633f18dfd.png)

In your case, the error occurs after L1R conversion, and it seems to be before the sensor specific LUTs are loaded. This indicates there could be a problem with loading either the ancillary data or the hyperspectral gas transmittance LUT. Could you list the files in your acolite/data/LUT directory? Perhaps you can delete the files there and try the run again. 

It could be that the NetCDF LUTs were downloaded incompletely or not at all. If there are no files there, perhaps you can try a different network connection, or to manually obtain the files from the separate repository https://github.com/acolite/acolite_luts

If this doesn't help, attaching a copy of your settings file would be useful!

Quinten

**Comment by LH002** [comment]
[LUT_file_Landsat9.docx](https://github.com/acolite/acolite/files/8552714/LUT_file_Landsat9.docx)
These are my LUT files

**Comment by acolite** [comment]
At first glance these look fine - could you provide the settings files that were generated for this run?

**Comment by LH002** [comment]
[acolite_run_20220420_100540_l1r_settings_user.txt](https://github.com/acolite/acolite/files/8552809/acolite_run_20220420_100540_l1r_settings_user.txt)
This is my setting file

**Comment by acolite** [comment]
Could you try running with ancillary_data=False?

**Comment by LH002** [comment]
In this way, the processing can run successfully. But will setting this affect the results?

**Comment by acolite** [comment]
Did you set up an EarthData account for getting the ancillary data? e.g. https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?f=5&t=235

For the areas in this paper I found little difference between using the default settings and ancillary data: https://doi.org/10.1364/OE.397456

There could be larger differences if the atmosphere is really dry or really humid. For pressure and ozone the defaults are probably fine if your target is at around sea level. If your target is at significant elevation, specifying the elevation value in metres or using a DEM would probably be fine. 

Quinten

**Comment by LH002** [comment]
Thank you veay much! I have an  EarthData account, meybe it limited by network speed. But after checking your reply, I can rest assured to use the default settings. Thank you！
