### ISSUE TITLE
Error No module named gdal

### ISSUE THREAD

**Issue by robibck** [acolite/acolite#34]
Hello,
I am trying to get acolite to work on my sentinel data. I am using anaconda on windows 10. I have created my acolite environment and installed all the packages as explained. I have tried several times to install the gdal package, uninstall and reinstall everything... 

![erreur gdal](https://user-images.githubusercontent.com/94461795/167521268-de81cafa-a3da-42f1-9e32-8b2730cf1016.png)

My Python and gdal version are here
![python infos](https://user-images.githubusercontent.com/94461795/167522645-151252d2-f4df-4ade-bd72-9d436b1a4df2.png)

I have checked that gdal was installed by importing it and everything works...
If you have a solution, I'm interested ! Thanks for your answers !
Have a nice day ;-)

**Comment by acolite** [comment]
It looks like you are using the previous version ([acolite_ls2](https://github.com/acolite/acolite_ls2)), which is no longer maintained or supported. The best solution would be to update to the code from the present repository ([acolite](https://github.com/acolite/acolite)).

I do recommend switching to the current code base, but alternatively you could probably fix the gdal import in the nc_to_geotiff.py script by changing the import line to:

`from osgeo import osr, gdal`

(Not explicitly tested, and this almost starts to look like support for the older version, which I am not supporting! ;-)) 

Quinten

**Comment by robibck** [comment]
Thank you very much ! 
I downloaded the new version that you linked and it worked !
Have a nice day ;-)
Rob
