### ISSUE TITLE
hgt_dir Path Sometimes Gains Double '//' when Using SRTMGL3 DEM 

### ISSUE THREAD

**Issue by bwakefie** [acolite/acolite#40]
We have ACOLITE running in Docker containers in AWS Fargate. We have our own SRTMGL3 DEM data, which we transfer from S3 to each container as it runs. In our case, `source = 'srtmgl3'` so the default [hgt_dir](https://github.com/acolite/acolite/blob/9a038815290e79704191382dbff80bb1245c5152/config/config.txt#L21) value should be `hgt_dir=$ACDIR/data/SRTM/` , so we're transferring the .zip files to `./data/SRTM/SRTMGL3/` . Occasionally, I see this error:

`SRTM DEM: /acolite/data/SRTM/SRTMGL3//N37W075.SRTMGL3.hgt.zip does not exist` (note the "//")

I believe this may be due to [Line 21 in hgt_lonlat.py](https://github.com/acolite/acolite/blob/main/acolite/dem/hgt_lonlat.py#L21) , which looks like after the string expansion may add the second "/" because it is trying to append the strings `./data/SRTM/` with `/SRTMGL3`, resulting in `./data/SRTM//SRTMGL3`

NOTE: I only notice this issue about 50% or the time, which doesn't make sense to me; I would expect this to happen every time if it truly is the `hgt_dir+=/SRTMGL3/` line, so I'm hoping there is an obvious explanation I'm missing.

My motivation for resolving this is that we are running a large number of jobs, and I'm trying to limit the amount of internet traffic for the sake of our network. I would prefer not to download the SRTM data because we already have it in our VPC in S3.

**Comment by acolite** [comment]
Thanks for the report! Cool to see you are running ACOLITE on AWS!

I believe the main issue here is that ACOLITE is trying to get SRTM tiles that do not exist (e.g. over the open ocean). Double slashes in the path should be ignored, although it is not pretty and it may be better to fix this as well.

In the current implementation, the required SRTM tile names are computed based on the latitude and longitude extent of the scene or subscene. There is no test whether those tiles actually exist, apart from trying to download the tile from the USGS server. Missing tiles are filled with zeros which is probably fine over the ocean, but you will get an attempt to download the tile each run. (This should not use a lot of bandwidth, but you may still want to avoid repeated attempts at getting a resource that doesn't exist.)

To fix this I will need to include a list of tiles based on the files on the USGS server, like I did recently for the GED (https://github.com/acolite/acolite/blob/main/data/GED/AG100.003_tilelist.txt). I will implement this when I get back to work after my holidays! 

The output results with or without the tile checks should be the same, as missing tiles will be dealt with in the same manner, i.e. by setting elevation to 0.

Quinten

**Comment by bwakefie** [comment]
Thanks for the thoughts, Quinten! The thing is, I'm fairly confident the SRTM files exist, because I'm successfully transferring them from our S3 bucket to the container running in Fargate. We do have some scenes from tiles with ocean in them, but never less than 50%ish land overage in those tiles. You said something that caught my ear: for GED you have a text file with a list of DEM files. We do something similar, with a JSON file that has a list of SRTM files for each tile, like so:

`"T16RFT": "N29W086.SRTMGL3.hgt.zip,N29W085.SRTMGL3.hgt.zip",`
`"T16RGT": "N29W085.SRTMGL3.hgt.zip,N29W084.SRTMGL3.hgt.zip",`

For each scene we process, we extract an array of SRTM files for that scene's tile ID, then transfer the necessary SRTM files from S3 in a for loop like so:

`for srtmfile in ${SRTMFILES[@]}; do`
  `aws s3 cp s3://ngwos-rswq-development/srtm/$srtmfile /acolite/data/SRTM/SRTMGL3/`
`done`

We then later when while ACOLITE CLI is running, I see this output that looks relevant:

`Extracting srtm DEM   data`
`http://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL3.003/2000.02.11/N37W075.SRTMGL3.hgt.zip` `/acolite/data/SRTM/SRTMGL3//N37W075.SRTMGL3.hgt.zip`
`SRTM DEM:   /acolite/data/SRTM/SRTMGL3//N37W075.SRTMGL3.hgt.zip does not exist`

Thoughts? All this being said, I could be missing something. My role in the project is to implement the code the scientists have written in the cloud, so I'm very new to remote-sensing and the atmospheric correction process. I'll also email you two CloudWatch log streams, one when the SRTM files are downloaded via HTTP and one where the local SRTM files are successfully used. Thanks again!

Brendan

**Comment by bwakefie** [comment]
I will also say, we've had some bugs in the past extracting the SRTM files from our JSON document, so it could be that like you say this isn't an issue with the double `//` and that the lat/long calculation ACOLITE performs comes up with a list of needed SRTM files that is different from the files I've transferred to `/acolite/data/SRTM/SRTMGL3/`.

I am writing the list of SRTM files transferred to the container to the output (logs). Do you have a suggestion for how best to see the array stored in [hgt_required](https://github.com/acolite/acolite/blob/ec6e33ab28ad62c553b298b1c3e5abdebf553286/acolite/dem/hgt_find.py#L30) that ACOLITE is expecting to find? I could see if there is a mismatch.

**Comment by bwakefie** [comment]
Quintin, I believe I found our issue: I had assumed that if I saw HTTP downloads of the SRTM files it was re-downloading _all_ SRTM files for that scene's tile. However I've looked more closely and am realizing that it appears ACOLITE is downloading SRTM files that are missing from our collection. I think you're correct, it only downloads SRTM files over HTTP when it's missing from the container (was never transferred from S3), and the double `//` is just an artifact of the string printing in the error message. This message is indicating which SRTM file is _missing_:

`/acolite/data/SRTM/SRTMGL3//N37W075.SRTMGL3.hgt.zip`

I'll close this issue as resolved and delete my PR. Feel free to delete the issue or PR to keep the repo cleaner. Thank you for the help!

Brendan

**Comment by bwakefie** [comment]
I further confirmed in the ACOLITE *_log.txt output file that the HTTP request happens before the "does not exist" message, so I believe this is further evidence the file is not downloaded, and that's the reason ACOLITE reports that it's missing:

`2022-08-30 02:09:39: Extracting srtm DEM data`
`2022-08-30 02:09:46: http://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL3.003/2000.02.11/N39W074.SRTMGL3.hgt.zip`
`2022-08-30 02:09:46: /acolite/data/SRTM/SRTMGL3//N39W074.SRTMGL3.hgt.zip`
`2022-08-30 02:11:57: SRTM DEM: /acolite/data/SRTM/SRTMGL3//N39W074.SRTMGL3.hgt.zip does not exist`

(Previously, I hadn't seen these timestamps, since all the acolite output is written at the same instant in CloudWatch logs.)

I also confirmed that this SRTM file **N39W074.SRTMGL3.hgt.zip** does not exist at https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL3.003/2000.02.11/index.html

**Comment by acolite** [comment]
Hi Brendan

Thanks for the additional info. To avoid attempting to get non existent tiles, I will add a list of tiles. A single query to the USGS server can take a few minutes so it makes sense not to repeatedly try for those non existent files! I will post here when that update is in place. (Next week or the week after.) 

The Copernicus DEM is also available on AWS which may be an alternative option: https://registry.opendata.aws/copernicus-dem/

Quinten

**Comment by bwakefie** [comment]
Thanks Quinten for the effort Quinten! The request for the nonexistent files appears to only take a second or two from the logs I've looked at, but we're also running 1000s of jobs so I'm sure our friends "across the hall" at EROS will appreciate cutting unnecessary requests.

**Comment by acolite** [comment]
Hi Brendan

I added tile lists for SRTM GL1 and GL3. This should hopefully stop attempts at getting non-existent tiles. Let me know if this works for you.

Quinten

**Comment by bwakefie** [comment]
Thank you for adding that Quinten! I appreciate the quick update. I'll be sure to let you know if I see any improvements or issues. I believe I coincidentally built in a metric that will allow me to record the number of times my container pings *.cr.usgs.gov, so if it works I can let you know if your addition fixes the issue.

I shot you an email asking for some follow-up advice regarding acolite versioning.

Brendan
