### ISSUE TITLE
Not able to detect PHR bundle

### ISSUE THREAD

**Issue by ruz76** [acolite/acolite#44]
Clone of the code from 20221020 was not able to detect PHR bundle. I am still not sure why, the code seems to be correct, but I had to change [acolite/pleiades/bundle_test.py](https://github.com/acolite/acolite/blob/main/acolite/pleiades/bundle_test.py) on line 38 to:

```python
dtype = tmp[1]
dataset = tmp[2]
```

This fix my issue. Without this change the original code

```python
_, dtype, dataset = tmp
```
produces empty variables.

Run on Python 3.8.10. Ubuntu Linux 20.04.1.

**Comment by acolite** [comment]
Thanks for your report - I am not sure why the one version would work and not the other! Would it be possible to share the bundle or the VOL_PHR.XML file for testing purposes?

Quinten

**Comment by ruz76** [comment]
I am not sure as well. This is really strange. Here is the VOL_PHR.XML. Unfortunatelly I can not share the whole bundle.
[VOL_PHR.XML.zip](https://github.com/acolite/acolite/files/9835770/VOL_PHR.XML.zip)

I was not precise in the description. The dtype is not empty, but the code after line 38 is not executed. I have no idea why.

```python
tmp = title.split(' ')
print(tmp)
if tmp[0] not in ['SENSOR','ORTHO','SYSTEM_ORTHO']: continue
print("NO CONTINUE")
print(tmp)
_, dtype, dataset = tmp
print("AFTER TMP")
print("dtype: " + dtype)
```

```output
Running ACOLITE processing - Generic GitHub Clone c2022-10-20T14:12:04
Python - linux - 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
Platform - Linux 5.15.0-46-generic - x86_64 - #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022
Run ID - 20221021_065417
['ORTHO', 'P', 'PHR', 'Volume', 'Description']
NO CONTINUE
['ORTHO', 'P', 'PHR', 'Volume', 'Description']
/tmp/xa not recognized.
Not deleting extracted file as "delete_extracted_input" is not in settings.
```

**Comment by ruz76** [comment]
I have tried the code in separate file and got this error.

```python
title = 'ORTHO P PHR Volume Description'
tmp = title.split(' ')
print(tmp)
_, dtype, dataset = tmp
print("AFTER TMP")
print("dtype: " + dtype)
```
```output
['ORTHO', 'P', 'PHR', 'Volume', 'Description']
Traceback (most recent call last):
  File "omg.py", line 4, in <module>
    _, dtype, dataset = tmp
ValueError: too many values to unpack (expected 3)
```
So this is a problem that my Python is not able to unpack just three variables from 5 items list.
Your version of Python is probably capable to do it or your testing VOL_PHR.XML has just three items in the title.

I am not using such construct (_, dtype, dataset = tmp), so I do not know how it should or should not work. I always use indexing when I want to use value directly from list.

Maybe the cleanest fix is:
```python
if tmp[0] not in ['SENSOR','ORTHO','SYSTEM_ORTHO']: continue
components.append({'title':title,'path':path, 'type': tmp[1], 'dataset': tmp[2]})
```
or
```python
if tmp[0] in ['SENSOR','ORTHO','SYSTEM_ORTHO']:
    components.append({'title':title,'path':path, 'type': tmp[1], 'dataset': tmp[2]})
```

**Comment by acolite** [comment]
Well my version of Python also doesn't support that, it's just that I never had >3 elements in the COMPONENT_TITLE with 'SENSOR','ORTHO','SYSTEM_ORTHO' , so this bad part of code didn't interfere yet. :-)

I had already committed your first suggestion based on tests similar to those in your second  post, before I saw the follow up post with other suggestions I also like 

Anyway this should be fixed, but I may use one of your later suggestions in the future https://github.com/acolite/acolite/commit/8a4b3a2fefc159d388b3aac526c9d4560540256e

Quinten

**Comment by ruz76** [comment]
Thank you

**Comment by acolite** [comment]
For reference, in my bundles the third element in COMPONENT_TITLE is the file name. The elements 3-5 in your title are "PHR Volume Description". I am not sure if using "PHR" as dataset will not interfere later in the processing. Can you confirm the bundle processes fully with these edits?

(It's difficult to track precise functioning of various bits of code, especially for private assets! :-))

Quinten

**Comment by ruz76** [comment]
Yes. it was able after this fix continue and produce results into output directory.
