### ISSUE TITLE
Identical products with different Product Discriminator - ROI in 100% blackfill

### ISSUE THREAD

**Issue by EmanuelCastanho** [acolite/acolite#45]
Inside a folder called `S2L1C_Products` I have two SAFE folders:
- S2A_MSIL1C_20220430T090601_N0400_R050_T35SMD_20220430T100927.SAFE
- S2A_MSIL1C_20220430T090601_N0400_R050_T35SMD_20220509T093247.SAFE

I am processing them with ACOLITE for the `ROI = {"type":"Polygon","coordinates":[[[26.518351,39.037467],[26.518351,39.046865],[26.534146,39.046865],[26.534146,39.037467],[26.518351,39.037467]]]}` which is in a part of the tile without data (ROI is red rectangle):

<img width="1079" alt="Screenshot 2022-10-20 at 21 33 56" src="https://user-images.githubusercontent.com/69935277/197065537-8a2241ed-ed25-4b7b-a9d3-ce2d53edc713.png">

Results are being saved to `ACOLITE_Outputs` folder.

Some of my ACOLITE parameters include:
```
# Delete NetCDFs L1R, L2R, L2W .nc files in output folder
settings['l1r_delete_netcdf'] = True
settings['l2r_delete_netcdf'] = True
settings['l2w_delete_netcdf'] = True
# Delete settings and log files are deleted in output folder
settings['delete_acolite_run_text_files'] = True
```

This is producing the following error:
```
File "/Users/.../Configs/acolite-main/acolite/acolite/acolite_run.py", line 245, in acolite_run
    os.remove(f)
FileNotFoundError: [Errno 2] No such file or directory: 'ACOLITE_Outputs/S2A_MSI_2022_04_30_09_19_33_T35SMD_L1R.nc'
```

It seems to be that ACOLITE is having difficulties with identical products with different Product Discriminator where the ROI is in no data zone, did anyone else experienced this?

**Comment by acolite** [comment]
Hi Emanuel - thanks for your report! Could you clarify which version of ACOLITE you are using?

These files generate the same ACOLITE output names, and it seems the version you are using does not test whether the path exists before deleting the file. So when running through the outputfiles it tries to delete the same file twice, which fails. This test (if os.path.exists(f):) is present in the current version of acolite_run.py and line 245 does not correspond to os.remove(f) as is reported in your error.

If you have more such duplicate bundles and want to keep both files you can e.g. add the bundle identifier to the output directory path, adding another directory level. (I expect the outputs for such bundles to be the same, but I'd be curious to hear otherwise!) 

There was a user with similar duplicate bundles, but I never heard back from them (https://github.com/acolite/acolite/issues/36) I suggested there to merge the bundles if they have different sensing coverage.

Quinten

**Comment by EmanuelCastanho** [comment]
Hi, I am having difficulties checking the version of ACOLITE since I cloned the folder from GitHub (`Running ACOLITE processing - Generic GitHub Clone`). Which file has the version information?
My colleague seems to be using the most recent version of ACOLITE since the files are being properly deleted!

When you say: "I expect the outputs for such bundles to be the same, but I'd be curious to hear otherwise!"
I found these two products:
- S2A_MSIL2A_20200210T073031_N0214_R049_T37MEU_20200210T130912
- S2A_MSIL2A_20200210T073031_N0214_R049_T37MEU_20200210T100652

I thought they would had the same information, but they are different according to: [Issue](https://github.com/stactools-packages/sentinel2/issues/5). But we are not having overwrited results!

Thank you for your reply!

**Comment by acolite** [comment]
It seems like you could use an update of the code (git pull). Newer versions printout the date of last git pull (or git clone date) at the start of a run.

I will take a look at the duplicate scenes! Perhaps the sensing time is different leading to slight differences in ACOLITE output file naming. If they contain complimentary data you can perhaps merge them for your ROI.

Quinten

**Comment by acolite** [comment]
Hi Emanuel

I have added support for merging full tiles. I have also added the s2_dilate_blackfill option to get rid of the seam between the two datasets. I have tested with the images you listed above (well the L1C version of those): S2A_MSIL1C_20200210T073031_N0209_R049_T37MEU_20200210T092906.SAFE and S2A_MSIL1C_20200210T073031_N0209_R049_T37MEU_20200210T095053.SAFE

Using merge_tiles=True just by itself this gives a seam between the data in both scenes:

With the tile ending in 20200210T092906 listed first in inputfile:
![S2A_MSI_2020_02_10_07_50_15_merged_L1R_rgb_rhot](https://user-images.githubusercontent.com/26734727/202859194-8c7be4a4-6cf2-42d1-99cc-3007cbf5e2a4.png)

With the other tile listed first:
![S2A_MSI_2020_02_10_07_50_08_merged_L1R_rgb_rhot](https://user-images.githubusercontent.com/26734727/202859221-83139a15-c479-4fc5-bfbb-5170e768037e.png)

With merge_tiles=True and s2_dilate_blackfill=True this gives (the order in which the scenes are given is not important here):
![S2A_MSI_2020_02_10_07_50_15_merged_L1R_rgb_rhot](https://user-images.githubusercontent.com/26734727/202859320-21295657-d0c4-43f5-bbdd-1b0fe5086ff6.png)

I hope this is useful! Please let me know if you have further questions regarding this issue.

Quinten
