### ISSUE TITLE
Problem with interpolation

### ISSUE THREAD

**Issue by yrzhanov** [acolite/acolite#46]
Hello, I'm trying to work with Sentinel-2 data (specifically, L1C_T17RLH_A008531_20170208T160849). ACOLITE exits with the following:
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "acolite\acolite\acolite_gui.py", line 30, in run
  File "acolite\acolite\acolite_gui.py", line 25, in run
  File "multiprocessing\process.py", line 108, in run
  File "acolite\acolite\acolite_run.py", line 121, in acolite_run
  File "acolite\acolite\acolite_l2r.py", line 468, in acolite_l2r
  File "scipy\interpolate\interpolate.py", line 2506, in __call__
ValueError: The requested sample points xi have dimension 6, but this RegularGridInterpolator has dimension 5
Processing error:
The requested sample points xi have dimension 6, but this RegularGridInterpolator has dimension 5
Traceback (most recent call last):
  File "acolite\acolite\acolite_gui.py", line 25, in run
  File "multiprocessing\process.py", line 108, in run
  File "acolite\acolite\acolite_run.py", line 121, in acolite_run
  File "acolite\acolite\acolite_l2r.py", line 468, in acolite_l2r
  File "scipy\interpolate\interpolate.py", line 2506, in __call__
ValueError: The requested sample points xi have dimension 6, but this RegularGridInterpolator has dimension 5

Is it something to do with the relatively old data?

Thanks,
    Yuri Rzhanov

**Comment by yrzhanov** [comment]
I'd like to add that with other data, for example, L1C_T17RMH_A023289_20210821T160427, the same version works fine.

Yuri

**Comment by yrzhanov** [comment]
I noticed that the processing of other files (for example, L1C_T17RMH_A023289_20210821T160427) goes fine. The main difference between logs are that L1C_T17RMH_A023289_20210821T160427 8 tiles (2x4) are processed, in case of L1C_T17RLH_A008531_20170208T160849 16 tiles (4x4). Also, after loading LUT wavelength 442 is being processed (1 rhot_442), while in the failing case 443 (1 rhot_443).
Yuri

**Comment by acolite** [comment]
Hi Yuri

Thanks for the report, I suspect you may need to update your ACOLITE. Could you clarify which version of ACOLITE you are using, and on which platform? Could you provide your settings and log files? (If you prefer, sharing these files can be done privately through email.)

The scene S2A_MSIL1C_20170208T160411_N0204_R097_T17RLH_20170208T160849.SAFE (from L1C_T17RLH_A008531_20170208T160849.zip obtained via EarthExplorer) processes fine here using the latest binary (20221025.0) and GitHub code using default settings.

![S2A_MSI_2017_02_08_16_08_49_T17RLH_L2R_rgb_rhos](https://user-images.githubusercontent.com/26734727/199165744-b3caf72a-e3fc-4b61-aa11-b04dfc4d3cfa.png)

Quinten

**Comment by yrzhanov** [comment]
Thank you for replying. I used version 20211124.0 on Windows 10. Settings and log file are attached. I did not think about updating ACOLITE because it worked fine with the same file (SAFE folder) couple of years ago. Will try to get the latest version and report the result.
Thank you,
    Yuri

[AcoliteSettings-20170208.txt](https://github.com/acolite/acolite/files/9909605/AcoliteSettings-20170208.txt)
[acolite_run_20221030_085741_log_file.txt](https://github.com/acolite/acolite/files/9909613/acolite_run_20221030_085741_log_file.txt)

**Comment by yrzhanov** [comment]
Reporting: everything is working fine. Probably somewhen between 2 years ago and 1 year ago some bug creeped in. Now it's gone. Thank you.
    Yuri
