### ISSUE TITLE
the package logging is confict with built-in logging！ may be need to rename it

### ISSUE THREAD

**Issue by lwk1542** [acolite/acolite#49]
acolite->acolite->logging

**Comment by acolite** [comment]
This has not come up before. Could you describe how you are using ACOLITE and what exactly is the problem?

**Comment by lwk1542** [comment]
> 

I used Acolite in my  Python environment.  The PIL package has been installed. When the PIL needs to call the logging from the built-in function， the program will priority call the acolite. logging. Error occurring. If i renamed the logging of acolite as logging_cus, no error occurring.

<img width="307" alt="微信图片_20221118194226" src="https://user-images.githubusercontent.com/16815156/202699364-5729686f-87ed-4eb0-95c8-cd4297710fc7.png">

**Comment by lwk1542** [comment]
> 

![QQ截图20221118200711](https://user-images.githubusercontent.com/16815156/202701868-75784942-c7ad-43f5-8ab2-49542eecb1e5.jpg)

**Comment by acolite** [comment]
I presume ACOLITE is not properly added to your path. You need to add the path to the main acolite directory, and not any of the subdirectories. I believe you downloaded the zip file from GitHub and extracted to acolite-main, so this is the directory that needs to be added to your path, not acolite-main/acolite or acolite-main/acolite/acolite.

I can load ACOLITE, logging, and PIL without issues in the same environment. 

Here I have directly cloned acolite to a "git" directory in my home folder:
![acolite_logging](https://user-images.githubusercontent.com/26734727/202709058-74696769-6525-4ab3-a60a-6d0cf07532d7.png)

Here I have downloaded the ZIP from GitHub and extracted in my "Downloads" folder:
![acolite_logging2](https://user-images.githubusercontent.com/26734727/202709411-951a66f5-644a-4b46-9274-35ca7493dccb.png)

I hope this helps!

Quinten
