### ISSUE TITLE
Reading metadata of PHR file with empty alpha channel description

### ISSUE THREAD

**Issue by ruz76** [acolite/acolite#50]
We have PHR file that contains metadata, that are in quite strange state, but they are original from distributor. Acolite is not able to read them. 

Problematic part is this one (ALPHA_CHANNEL):
```
<Band_Display_Order>
                <RED_CHANNEL>P</RED_CHANNEL>
                <GREEN_CHANNEL>P</GREEN_CHANNEL>
                <BLUE_CHANNEL>P</BLUE_CHANNEL>
                <ALPHA_CHANNEL></ALPHA_CHANNEL>
</Band_Display_Order>
```

We are getting NoneType error.

I sugget to fix this by changing pleiades/metadata_parse.py 

Line 34: 
`if len(node) > 0: metadata[tag] = node[0].firstChild.nodeValue`

to:
```
if len(node) > 0:
   if not node[0].firstChild is None:
       metadata[tag] = node[0].firstChild.nodeValue
```
[DIM_PHR1B_P_202204221101235_ORT_f2590ae3-91a8-432e-c320-c67276efc058-002.XML.zip](https://github.com/acolite/acolite/files/10077787/DIM_PHR1B_P_202204221101235_ORT_f2590ae3-91a8-432e-c320-c67276efc058-002.XML.zip)

I attached the metadata file.

**Comment by ruz76** [comment]
I have created pull request for this. 
Thank you very much for acceptance in advance.

**Comment by acolite** [comment]
Thanks, I will take a look!

This looks very familiar, I had a very similar issue yesterday with parsing some Gaofen-1 metadata: https://github.com/acolite/acolite/blob/ca4ae4fec8b48634a2b8dd5c49a15612e90daab1/acolite/gf/metadata.py#L41

Quinten
