### ISSUE TITLE
About l1_convert.py (GF)

### ISSUE THREAD

**Issue by dumpling827** [acolite/acolite#53]
Dear supporters, 
In line 46 of this python file (acolite/acolite/gf/l1_convert.py), it gives a 'dn_bias' which is 0.2. 
But I find the PDF given in line 31, and it says that the default bias of GF 1/2/4/6 (table 1 of PDF) is 0. 
I am not sure if I misunderstand.

![bias](https://user-images.githubusercontent.com/82812439/205617037-0b885576-c4a1-46c9-8ba2-ac16403e6363.png)

Thanks! : )

**Comment by acolite** [comment]
Thanks for your comment! I believe the application of a 0.2 bias is correct. There is a note at the bottom of the three page PDF document (240A9946ECED64C3CB4D56B8A8764F35) I have:

![GFbias](https://user-images.githubusercontent.com/26734727/205633701-9708a3f9-2987-4ad2-9d86-e7974f89a0d3.png)

I cannot read Chinese, but Google translate tells me the marked section "没有标注 Bias 值的情况下代表 Bias 值为 0。2" reads "If the Bias value is not marked, it means that the Bias value is 0.2". 

Please let me know if you have other information or an updated version of this PDF. I believe also the offset was needed to get rid of some TOA negatives in the imagery I have, but I may be misremembering.

I hope this helps!

Quinten

**Comment by dumpling827** [comment]
谢谢，您发的邮件我已收到。

**Comment by dumpling827** [comment]
Dear Quinten, 
Thanks for your reply! 
I think it's a misunderstanding caused by different languages. 
In the line you marked, '2)' represents a serial number (the same as '1)' in the front) and the dot between 0 and 2 is a period but not a decimal point.

**Comment by acolite** [comment]
Thanks, that actually makes sense. :-) Did you try processing with a bias = 0? Were the results better?

Quinten

**Comment by dumpling827** [comment]
Sorry, I didn't compare the results of different biases. : )

**Comment by acolite** [comment]
I tested with both bias values and found only small differences. 

Bias of 0.2:
![oldbias](https://user-images.githubusercontent.com/26734727/206858000-75fabd59-f665-4e32-94b4-8210ef2176c8.png)

Bias of 0.0:
![newbias](https://user-images.githubusercontent.com/26734727/206858016-d6bb50e3-c9f1-41c8-a8dd-e0c3afbf7788.png)

I have now committed the change with bias=0. Thanks for your report!

Quinten
