### ISSUE TITLE
Acolite_20221114 problem with variable 'setu'

### ISSUE THREAD

**Issue by yrzhanov** [acolite/acolite#59]
Hello, I have the latest binary executable 20221114. With the new Copernicus Sentinel hub Acolite fails with the following:
Processing error:
local variable 'setu' referenced before assignment
Traceback (most recent call last):
  File "acolite\acolite\acolite_gui.py", line 26, in run
  File "multiprocessing\process.py", line 108, in run
  File "acolite\acolite\acolite_run.py", line 91, in acolite_run
  File "acolite\acolite\acolite_l1r.py", line 73, in acolite_l1r
  File "acolite\sentinel2\l1_convert.py", line 751, in l1_convert
UnboundLocalError: local variable 'setu' referenced before assignment

I checked with the previous Sentinel-2 data bundles - works fine. It seems that something has changed in the downloaded data that Acolite cannot deal with.
Thanks,
    Yuri

**Comment by acolite** [comment]
Hi Yuri

It would be helpful if you could give more details in a bug report (e.g. user settings, scene identifier). 

As far as I know there has not been any reformatting of the Sentinel-2 data. I believe this error is caused by your trying to process a L2A and not a L1C file. Can you check the file you are trying to process?

Quinten

**Comment by yrzhanov** [comment]
Hi Quinten,

You are absolutely right – I was just so used to L1C product that did not pay attention that L2A product is now available… Sorry for that.

 

Cheers,

    Yuri

**Comment by acolite** [comment]
Thanks for the update - I did add an empty setu a few weeks ago (https://github.com/acolite/acolite/commit/573dc975d501801b7821c88f23e1130e9b13292c) which should solve the crash when running from the code and in future binaries.

Quinten
