### ISSUE TITLE
pleiades/l1_convert.py

### ISSUE THREAD

**Issue by datalass1** [acolite/acolite#6]
In the pleiades l1_covert script a KeyError bug exists in line 240 where `data /= meta['mus']` is run. The variable meta does not have a key mus, instead it should be `data /= gatts['mus']` . 

I have fixed this locally and the acolite correction script works for pleiades data now, so it just needs updated on github. 

Thanks, Rachel

**Comment by acolite** [comment]
Thanks Rachel! I think I didn't have a "reflectance" Pléiades image to test that part! :-)

Should be fixed in the l1_convert script for Pléiades data.

Quinten
