### ISSUE TITLE
Error opening metadata file for SDGSAT

### ISSUE THREAD

**Issue by danjac94** [acolite/acolite#60]
Running ACOLITE processing on win32
ACOLITE processing messages will be logged to file.
Running ACOLITE processing - Generic GitHub Clone c2023-04-13T14:18:11
Python - win32 - 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:50:54) [MSC v.1934 64 bit (AMD64)]
Platform - Windows 10 - AMD64 - 10.0.19045
Run ID - 20230417_132757
Error opening metadata file.
Error opening metadata file.

**Comment by acolite** [comment]
Could you provide some more information on this run? Could you send me via email e.g. the settings and log files? If possible, please send me a download link for the inputfile as well.

I presume there is an issue with the file encoding of the metadata, or the path to the metadata files.

Quinten

**Comment by acolite** [comment]
Processing worked fine, settings were not correctly configured.
