### ISSUE TITLE
QGIS can stop ACOLITE from working

### ISSUE THREAD

**Issue by EmanuelCastanho** [acolite/acolite#62]
So, this is only a detail, but maybe it is a good idea to register here.

I opened one of Sentinel-3 bands in QGIS-LTR, then closed the software. When you do this, QGIS saves an auxiliar xml file inside the SEN3 folder. 

<img width="1191" alt="Screenshot 2023-06-09 at 11 17 45" src="https://github.com/acolite/acolite/assets/69935277/b9030372-d5ef-44ca-baf0-94d115e5e898">

This stops ACOLITE from working.

![Screenshot 2023-06-09 at 11 18 15](https://github.com/acolite/acolite/assets/69935277/1fbb12a9-c4c1-49eb-a92a-dca2e460fc39)

`UnboundLocalError: local variable 'xmldoc' referenced before assignment`

**Comment by acolite** [comment]
Should now be fixed in the code: https://github.com/acolite/acolite/commit/6b84881161255baf063f4c7ccc9ddf0c87404676

Will be hence also fixed in future binary releases.

Quinten
