### ISSUE TITLE
Unable to automatically download LUTs for S3

### ISSUE THREAD

**Issue by EmanuelCastanho** [acolite/acolite#63]
Hi,

I am getting this error:

![Screenshot 2023-06-09 at 11 51 53](https://github.com/acolite/acolite/assets/69935277/d7b4de48-13ff-48a3-8c93-103d0383e9d2)

I tried the solution presented here: https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?t=294

![Screenshot 2023-06-09 at 11 54 24](https://github.com/acolite/acolite/assets/69935277/76e21706-ef91-48b1-8f13-baab7b61045d)

But it didn't work :/

I can manually download the file. Also, I am using the Source Code zip version from the latest release.

**Comment by acolite** [comment]
Did any folders get created in data/LUT/?

**Comment by EmanuelCastanho** [comment]
No folders created. 
I also manually created a folder called  Gas inside LUT to see if the download would start, but didn't change the error.

**Comment by EmanuelCastanho** [comment]
Okey, sorry about that, just found the reason for the error.
I forgot to install `requests` 🤦
