### ISSUE TITLE
Sentinel-3 OLCI Products have no CRS data

### ISSUE THREAD

**Issue by RAJohansen** [acolite/acolite#66]
Hello,

I have been using ACOLITE for processing both Sentinel-2 and Sentinel-3 (OLCI) products, and have no issues with the outputs from the sentinel-2 images (CRS is UTM), but the OLCI products have no CRS data and instead seem to have x & y values as just relative index locations of the pixels.

I am using default settings of the newest version of ACOLITE.

Has anyone else seen this issue?

**Comment by acolite** [comment]
Hi Richard

Sentinel-3 data are provided in swath geometry, and hence they do not have a geographic projection associated with them. You will need to reproject the data to a CRS of your choice.

I always recommend users to do their own reprojection, but it is possible to do this within ACOLITE, for example see here: https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?t=361 and maybe you'll find some useful information in this closed issue: https://github.com/acolite/acolite/issues/64

I hope this helps!

Quinten

**Comment by RAJohansen** [comment]
Perfect, thank you!
