### ISSUE TITLE
AOD

### ISSUE THREAD

**Issue by LH002** [acolite/acolite#7]
Hello, dear author, I would like to ask you, does acolite support the production of AOD products？

**Comment by acolite** [comment]
Aerosol optical depth at 550 nm can be output by setting dsf_write_aot_550=True in your settings file. 

Quinten

**Comment by LH002** [comment]
Thank you very much!

**Comment by LH002** [comment]
Dear Quinten, if I want to a AOD.giff , what should I do?  I used the"dsf_write_aot_550=True" in my setting file,but it producted a picture, but it isn't my wanted.         Thank you!

**Comment by acolite** [comment]
If you set dsf_write_aot_550=True, the aot_550 dataset is stored in the L2R NetCDF file, you can either access it directly from that file, or export the L2R data to GeoTIFF by setting l2r_export_geotiff=True

Alternatively, if you generate L2W products and already export L2W data to GeoTIFF using l2w_export_geotiff=True, you can also add "aot_550" to your l2w_parameters string.

Quinten

**Comment by LH002** [comment]
Dear Quinten,  I tried what you offered, but I still didn't get the aot.tiff file or find it in the L2R file , and its processing is accompanied by an error prompt.
![image](https://user-images.githubusercontent.com/35960535/127084551-2575e9e8-b804-495a-820a-42c17a63224f.png)
This is my setting file,
![image](https://user-images.githubusercontent.com/35960535/127084638-5fad00d0-16f9-4213-ae93-f6a23229d941.png)
This is an error message,now, how do I do?

**Comment by acolite** [comment]
Are you using the code from this repository, or the code from acolite_ls2?

**Comment by LH002** [comment]
The code from this repository

**Comment by acolite** [comment]
Could you send me your full settings and log files?

The error occurs on line 285 of acolite_run.py, which has only 159 lines in the current repository: https://github.com/acolite/acolite/blob/main/acolite/acolite/acolite_run.py

**Comment by LH002** [comment]
[acolite_run_tmp.txt](https://github.com/acolite/acolite/files/6889385/acolite_run_tmp.txt)
This is my setting file, but the log files I didn't find.

**Comment by acolite** [comment]
The error you are getting in line 285 is related to the spelling of the following settings:
l2r_export_geotiff=Flase
l2w_export_geotiff=Flase
"Flase" should be "False" and is then evaluated as a bool during import.

However the settings I described above for exporting aot_550 are for the generic acolite/acolite code and not for the older Landsat/Sentinel-2 specific acolite/acolite_ls2 code. They will likely have no effect when used in acolite_ls2.

**Comment by LH002** [comment]
Thank you very much.

**Comment by LH002** [comment]
When I using the generic acolite, there are some problems when it runs. How can I solve them?
This is the Error message：
![1627455659(1)](https://user-images.githubusercontent.com/35960535/127278446-dc2165fc-b42a-4760-9224-f64063a59365.png)
This is the setting :
![1627455707(1)](https://user-images.githubusercontent.com/35960535/127278548-1495f039-4e43-4526-a53a-3cd4387d328f.png)

**Comment by acolite** [comment]
You seem to have a newline character in the "West" coordinate. Can you check?

Do you have write permissions to F:/work/Acolite/20210728_OLI/?

**Comment by LH002** [comment]
Thank you! The first quession has been solved, but I haven't write permissions

**Comment by acolite** [comment]
Can you select an output location where you have write permissions?

**Comment by LH002** [comment]
Thank you very much for solving the problem for me. Is there any way to solve the problem when I installed osgeo?My system is win7

**Comment by acolite** [comment]
Presumably there is... But I don't know which problem you encountered when you installed osgeo, or the steps you took to install it.

I can not support all types of Python environment management, so I expect the users to have a working Python environment with dependencies installed. I have experienced good results with miniconda and conda-forge packages, as noted in the ReadMe.

**Comment by LH002** [comment]
Thank you for your helps!



---Original---
From: "Quinten ***@***.***&gt;
Date: Wed, Jul 28, 2021 18:01 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [acolite/acolite] AOD (#7)




 
Presumably there is... But I don't know which problem you encountered when you installed osgeo, or the steps you took to install it.
 
I can not support all types of Python environment management, so I expect the users to have a working Python environment with dependencies installed. I have experienced good results with miniconda and conda-forge packages, as noted in the ReadMe.

**Comment by LH002** [comment]
Dear Quinten,I encountered a problem when I ran it. This problem is "NameError: name 'lut_nc' is not defined". How do I do at this time?
Details are as follows:
Selected E:/BaiduNetdiskDownload/LC08_L1TP_119039_20201111_20201111_01_RT as input file.
Selected E:/Landsat8_aot as output directory.
Running ACOLITE processing on win32
ACOLITE processing messages will be logged to file.
Processing error:
name 'lut_nc' is not defined
Traceback (most recent call last):
  File "E:\Download\acolite-main\acolite-main\acolite\shared\lutnc_import.py", line 15, in lutnc_import
    nc = Dataset(lutnc)
  File "src\netCDF4\_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src\netCDF4\_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'E:\\Download\\acolite-main\\acolite-main\\data/LUT/Gas/Gas_202106F.nc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_gui.py", line 25, in run
    mp.Process.run(self)
  File "D:\python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_run.py", line 118, in acolite_run
    ret = ac.acolite.acolite_l2r(l1r, settings = setu, verbosity = verbosity)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_l2r.py", line 134, in acolite_l2r
    rsr=rsrd['rsr'])
  File "E:\Download\acolite-main\acolite-main\acolite\ac\gas_transmittance.py", line 18, in gas_transmittance
    tg_hyp = ac.ac.gaslut_interp(sza, vza, pressure=pressure, waves=waves, lutconfig=lutconfig)
  File "E:\Download\acolite-main\acolite-main\acolite\ac\gaslut_interp.py", line 32, in gaslut_interp
    lut, meta = ac.shared.lutnc_import(lutnc)
  File "E:\Download\acolite-main\acolite-main\acolite\shared\lutnc_import.py", line 26, in lutnc_import
    print(lut_nc)
NameError: name 'lut_nc' is not defined

**Comment by LH002** [comment]
Dear Quinten, I have a question about AOD products. There is no doubt that AOD products in acolite are suitable for water bodies. But is the product suitable for terrestrial ecological research?

**Comment by acolite** [comment]
In many cases the surface reflectance produced by ACOLITE over land seems OK, since the land reflectance is so much brighter than the water reflectances. Over vegetation the visible reflectance (especially blue) may be a bit worse, but at least  in the green-red/NIR/SWIR the results should be acceptable. We have not yet been able to collect enough validation data to confirm the land reflectance retrieval.

Quinten
