### ISSUE TITLE
Rayleigh scattering phase function, Omega

### ISSUE THREAD

**Issue by raphidoc** [acolite/acolite#72]
Hello Quentin,
I'm wondering about those two ways of calculating omega that yield different results:
https://github.com/acolite/acolite/blob/f1b78e383e8d1b8a41933b30fa8c912466d13303/acolite/acolite/acolite_l2r.py#L1527-L1528
So, the second calculation of Omega always overrides the first one. 
Which one is correct?

Thank you!

**Comment by acolite** [comment]
Hi Raphaël

It should be the second one, I have now removed the wrong line which was not used! :-)

Quinten
