### ISSUE TITLE
problems to correct S2 images in a fresh installation

### ISSUE THREAD

**Issue by mlzoffoli** [acolite/acolite#81]
Hi Quinten,
I just installed Python and ACOLITE on a new computer. I did't got any error during the installation, and successfully processed EMIT and PRISMA images. However, I got the following error when trying to run acolite for S2 images:

Processing error:
'NoneType' object has no attribute 'RasterXSize'
Traceback (most recent call last):
  File "C:\Users\Laura\acolite\acolite\acolite\acolite_gui.py", line 26, in run
    mp.Process.run(self)
  File "C:\Users\Laura\anaconda3\envs\acolite\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Laura\acolite\acolite\acolite\acolite_run.py", line 151, in acolite_run
    ret = ac.acolite.acolite_l1r(bundle)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Laura\acolite\acolite\acolite\acolite_l1r.py", line 79, in acolite_l1r
    l1r_files, setu = ac.sentinel2.l1_convert(bundle, settings = setu)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Laura\acolite\acolite\sentinel2\l1_convert.py", line 357, in l1_convert
    xSrc = g.RasterXSize
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'RasterXSize'

any thoughts of what could happen and how to resolve it?

thanks a lot in advance!
best,
Laura

**Comment by acolite** [comment]
Hi Laura

Have you opened the S2 bundle with QGIS or another program? It could be that these add files in the original bundle which ACOLITE does not like at the moment. You can check e.g. for .aux files in the granule folder.

A second option could be perhaps the file path length limitations in Windows. The S2 bundles have long file names, with several directory levels, and it is best to keep them on a low level directory on your drive.

I hope this helps!

Quinten

**Comment by mlzoffoli** [comment]
Hi Quinten,
Yes, I have verified the S2 data. I can open the image in SNAP and view individual granules in QGIS without any issues.  
The file is located in the Downloads folder, thus the path is relatively short: C:/Users/Laura/Downloads/S2B_MSIL1C_20240913T113319_N0511_R080_T29TNG_20240913T133039.SAFE

Do you have any other suggestions I could check to resolve the problem?
Thanks a lot for your help and prompt response!
best,
Laura

**Comment by acolite** [comment]
Hi Laura

Did QGIS put .aux files in the granule folder? This could be the problem. Please remove those files and try again.

Quinten

**Comment by mlzoffoli** [comment]
Hi Quinten,
no, I cannot see any .aux file in the GRANULE folder. I tried with another S2 image that just downloaded from the Copernicus Browser and before opening it in QGIS, and I get the same error.
I'm running acolite from the GUI, just in case it might be relevant to know
thanks again!
Laura

**Comment by acolite** [comment]
Hi Laura

All works fine here with various versions of the environment and the binary version. It seems the path length could be the issue on your system. It seems like the code has trouble accessing the band data, which in your case for band 1 would be at:

C:/Users/Laura/Downloads/S2B_MSIL1C_20240913T113319_N0511_R080_T29TNG_20240913T133039.SAFE/GRANULE/L1C_T29TNG_A039288_20240913T113318/IMG_DATA/T29TNG_20240913T113319_B01.jp2

Can you try moving the bundle e.g. to C:/Users/Laura/ or even better C:/?

If it is not that we may need to look into package versions.

Quinten

**Comment by acolite** [comment]
Hi Laura

I did now also test a brand new environment and found the same issue.  It seems it can be resolved by installing jp2openjpeg, e.g.

`conda install -c conda-forge libgdal-jp2openjpeg`

Quinten

**Comment by mlzoffoli** [comment]
Dear Quinten,
following your instructions I installed jp2openjpeg and it worked now!!
thanks a lot for your help!
best,
Laura
